# Generated by Django 5.2.4 on 2025-07-18 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('cuisine', 'Cuisine'), ('meal_type', 'Meal Type'), ('dietary', 'Dietary'), ('cooking_method', 'Cooking Method'), ('time', 'Time'), ('course', 'Course')], max_length=50)),
                ('color', models.CharField(help_text='hex color for UI', max_length=7)),
                ('icon_url', models.TextField(blank=True, help_text='optional icon for navigation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'unique_together': {('recipe', 'tag')},
            },
        ),
    ]
