# Generated by Django 5.2.4 on 2025-07-18 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(help_text='produce/meat/dairy/etc', max_length=100)),
                ('common_unit', models.CharField(help_text='grams/ml/pieces/etc', max_length=20)),
                ('dietary_flags', models.TextField(blank=True, help_text='JSON array: ["dairy", "gluten", "nuts", "soy", "eggs"] - what this ingredient contains')),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.IntegerField(help_text='minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_time', models.IntegerField(help_text='minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('base_servings', models.IntegerField(help_text='original recipe servings - used for scaling calculations')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('main_image_url', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='true/false for privacy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_numeric', models.DecimalField(decimal_places=3, help_text='250.0/125.5/etc for calculations', max_digits=10)),
                ('quantity_display', models.CharField(help_text='250g/1 1/2 cups for display', max_length=100)),
                ('unit', models.CharField(help_text='grams/ml/pieces/etc', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='optional: sifted, room temp, etc')),
                ('display_order', models.IntegerField(help_text='order in ingredient list')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='1,2,3...')),
                ('instruction', models.TextField()),
                ('estimated_time', models.IntegerField(blank=True, help_text='minutes for this step', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('alt_text', models.CharField(help_text='description for accessibility and display', max_length=255)),
                ('display_order', models.IntegerField(help_text='if multiple images per step')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipestep')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
